export const events = [
  {
    image: '/images/event1.png',
    title: 'React Summit 2026',
    slug: 'react-summit-2026',
    location: 'Amsterdam, Netherlands',
    date: 'June 5-6, 2026',
    time: '9:00 AM - 5:00 PM',
  },
  {
    image: '/images/event2.png',
    title: 'Next.js Conf',
    slug: 'nextjs-conf-2026',
    location: 'San Francisco, CA',
    date: 'October 21-22, 2026',
    time: '8:30 AM - 6:00 PM',
  },
  {
    image: '/images/event3.png',
    title: 'Developer Week Global',
    slug: 'developer-week-global',
    location: 'Virtual',
    date: 'July 13-17, 2026',
    time: '10:00 AM - 4:00 PM EST',
  },
  {
    image: '/images/event4.png',
    title: 'Tech Crunch Disrupt',
    slug: 'tech-crunch-disrupt-2026',
    location: 'San Francisco, CA',
    date: 'September 21-23, 2026',
    time: '9:00 AM - 5:30 PM',
  },
  {
    image: '/images/event5.png',
    title: 'JavaScript Global Summit',
    slug: 'js-global-summit-2026',
    location: 'Prague, Czech Republic',
    date: 'May 27-29, 2026',
    time: '8:00 AM - 6:00 PM',
  },
  {
    image: '/images/event6.png',
    title: 'Web Summit 2026',
    slug: 'web-summit-2026',
    location: 'Lisbon, Portugal',
    date: 'November 2-5, 2026',
    time: '9:00 AM - 7:00 PM',
  },
];
